export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  ROOM_EMPTY: "ROOM_EMPTY",
  ON_FILE_REQUEST: "ON_FILE_REQUEST",
  DOWNLOAD_PROGRESS: "DOWNLOAD_PROGRESS",
  SOCKET_CONNECTED: "SOCKET_CONNECTED",
};
